# -*- coding: utf-8 -*-
"""aula6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lne0RJn_Qmf3RUbReGEDcYmQIfVJRaBm
"""

# Online Python Playground
# Use the online IDE to write, edit & run your Python code
# Create, edit & delete files online
#nome = input("Qual é o seu nome? ")
#tamanho= len(nome)
#print (nome)
#print (tamanho)


#numero = int(input())
#tipo= type(numero)
#print(tipo)

# texto= input("digite um nome")
# lista = list (texto)
# comprimento = len(texto)
# print(lista,comprimento)
#numero_inteiro=10

# lista [1,2,3,4,5,6,7,8,9,78,45,24,579434,41,46,4132]
# maximo_da_lista=max(lista)
# minimo_da_lista=min(lista)

# lista  =  [1,2,3,4,456,5,6,78,9,10,11,12]

# minimo_da_minha_lista = min(lista)
# maximo_da_minha_lista = max(lista)
# organizar = sorted(lista)
# soma =  sum(lista)
# print('minimo - ', minimo_da_minha_lista)
# print('Maximo - ', maximo_da_minha_lista)
# print('Lista organizada', organizar)
# print('Soma da minha lista', soma)


#Exercício 1: Escreva um programa que use a função range() para gerar os números pares de 2 a 20 e, em seguida, imprima cada número
#for i in range(2,22,2):
    #print(i)


#Escreva um programa que use a função range() para gerar os múltiplos de 5 em 5 a 50 e, em seguida.
#for i in range(0,52,5):
 #   print(i)


 #Exercício 3: Escreva um programa que use a função type() para verificar o tipo de uma variável.
# numero = int(input ())
# tipo= type (numero)
# print(tipo)



# Escreva um programa que use a função print() para imprimir uma mensagem de saudação personalizada, incluindo o nome do usuário.
# nome= input("fale seu nome")
# print("bom dia")




#Exercício 5: Escreva um programa que use a função range() para gerar os números ímpares de 1 a 10 e, em seguida, calcule e imprima a média desses números.
# soma = 0
# x=5
# for c in range(1,11,2):
#    soma = soma + c
#    print(c)
# print("media:", soma /x)

#1 Imprima uma mensagem de boas-vindas na tela.
# nome = input('digite seu nome')
# print(nome,"ola seja bem vindo")

#2 Declare uma variável booleana verdadeiro com o valor True e imprima seu tipo
# boleana = True
# tipo= type (boleana)
# print(tipo)

#3 Imprima o resultado da multiplicação de dois números decimais de sua escolha
# numero_1= int(input())
# numero_2=50
# print(numero_1*numero_2)

#4 Imprima o resultado da divisão de dois números inteiros de sua escolha.
# numero_2= int(input())
# numero_1=50
# print(numero_1/numero_2)

#Imprima o resultado da subtração de dois números inteiros de sua escolha
# numero_1= int(input())
# numero_2=50
# print(numero_1-numero_2)

#8 Declare uma variável numero e atribua um número inteiro. Em seguida, imprima o dobro desse número
# numero_1= int(input())
# numero_2=numero_1**2
# print(numero_2)

#9 Crie uma calculadora de soma com as ferramentas que vc já conhece(Use apenas input, print e variavel)
# numero = int(input('digite seu primeiro numero'))
# numero_2= int(input('digite seu segundo numero '))
# soma= numero + numero_2
# print(soma)

#Crie um sistema de cadastro com as estruturas que vc já conhece(Use apenas input, print e variavel)
nome = input('digite seu nome')
idade= input('digite sua idade ')
telefone = input('digite seu telefone ')
print(  "Nome:",nome ,"Idade:",idade,"telefone:",telefone, 'cadastro realizado ')